[package]
name = "soroswap-factory-interface"
authors = ["esteblock <esteblock@paltalabs.io>"]
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
